# Generated by Django 2.1.3 on 2022-04-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmsSiteBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cms_site_booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmsSiteCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'cms_site_customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmsSiteFilm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('length_min', models.IntegerField()),
            ],
            options={
                'db_table': 'cms_site_film',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmsSiteReservedSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cms_site_reserved_seat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmsSiteRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('no_seats', models.IntegerField()),
            ],
            options={
                'db_table': 'cms_site_room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmsSiteScreening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'cms_site_screening',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmsSiteSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.CharField(max_length=1)),
                ('seat_number', models.IntegerField()),
            ],
            options={
                'db_table': 'cms_site_seat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('credits', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(blank=True, max_length=15, null=True)),
                ('sec_id', models.IntegerField(blank=True, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('building', models.CharField(blank=True, max_length=15, null=True)),
                ('room', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'section',
                'managed': False,
            },
        ),
    ]
