# Generated by Django 2.1.3 on 2022-04-04 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cmssitebooking_cmssitecustomer_cmssitefilm_cmssitereservedseat_cmssiteroom_cmssitescreening_cmssites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prereq',
            fields=[
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='course_course', serialize=False, to='myapp.Course')),
            ],
            options={
                'db_table': 'prereq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='student_id', serialize=False, to='myapp.Student')),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'takes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.Instructor')),
            ],
            options={
                'db_table': 'teaches',
                'managed': False,
            },
        ),
    ]
